// templates/frontend-angular/template/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  template: `
    <header>
      <nav>
        <a routerLink="/">Home</a>
        <a routerLink="/about">About</a>
      </nav>
    </header>
    <main>
      <router-outlet></router-outlet>
    </main>
  `,
  styles: [`
    header {
      background: #1a1a2e;
      padding: 1rem 2rem;
      margin-bottom: 2rem;
    }
    nav {
      display: flex;
      gap: 1rem;
    }
    nav a {
      color: #dd0031;
      font-weight: 500;
    }
    nav a:hover {
      color: #fff;
    }
    main {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 2rem;
    }
  `]
})
export class AppComponent {
  title = '{{project_name}}';
}

// templates/frontend-vue/template/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <header>
    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/about">About</RouterLink>
    </nav>
  </header>

  <main>
    <RouterView />
  </main>
</template>

<style scoped>
header {
  background: #1a1a2e;
  padding: 1rem 2rem;
  margin-bottom: 2rem;
}

nav {
  display: flex;
  gap: 1rem;
}

nav a {
  color: #42b883;
  text-decoration: none;
  font-weight: 500;
}

nav a:hover {
  text-decoration: underline;
}

nav a.router-link-active {
  color: #fff;
}

main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 2rem;
}
</style>
